ALTER TABLE collection_runs
ADD COLUMN IF NOT EXISTS raw_collected_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS usable_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS quality_dropped_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS deduplicated_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS duplicate_dropped_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS ranked_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS summary_candidates_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS summaries_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS used_cached_articles BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS used_cached_summaries BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS metrics_payload JSONB NOT NULL DEFAULT '{}'::jsonb;
