ALTER TABLE subscribers
ADD COLUMN IF NOT EXISTS frequency VARCHAR(20) NOT NULL DEFAULT 'diario',
ADD COLUMN IF NOT EXISTS preferred_time VARCHAR(20) NOT NULL DEFAULT 'manana',
ADD COLUMN IF NOT EXISTS consent_accepted BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS unsubscribed_at TIMESTAMP NULL;
